### ISSUE TITLE
18/03/2014

### ISSUE THREAD

**Issue by willa4you** [willa4you/ChessProjectVillaNegrini#7]
Cose da fare:
- riscrivere le classi del package model con nomi in inglese (Alessandro)
- lettere centrate sulle colonne della scacchiera con griglia globale 10x10 (Matteo)

**Comment by Th4nat0r** [comment]
Fatto la mia parte! (Matteo)

**Comment by willa4you** [comment]
Bravi. Ho fatto tutto io, ma non importa.
